---
# tasks file for nodejs
- name: Ensure old repository is not present
  become: true
  apt_repository:
    repo: ppa:chris-lea/node.js
    state: absent

- name: Add Nodesource package signing key
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add node.js repository
  become: true
  apt_repository:
    repo: "deb https://deb.nodesource.com/{{ nodejs.version }} {{ ansible_distribution_release }} main"
    state: present

- name: Add node.js source repository
  become: true
  apt_repository:
    repo: "deb-src https://deb.nodesource.com/{{ nodejs.version }} {{ ansible_distribution_release }} main"
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install nodejs apt package
  become: true
  apt:
    name: nodejs
    state: present
